name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET SDK 
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1.x'
      - run: cd TuneSearch/TuneSearch && dotnet build
      - run: cd TuneSearch/TuneSearch.Core.Tests && dotnet test
      - run: cd TuneSearch/TuneSearch.Infrastructure.Tests && dotnet test